# ?? App ??????????????????????????????????????????
spring.application.name=ecommerce-backend

# ?? Server ???????????????????????????????????????
server.port=8080

# ?? DataSource ???????????????????????????????????
spring.datasource.url=your-db-url
spring.datasource.username=your-username
spring.datasource.password=your-db-pasword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ?? JPA / Hibernate ??????????????????????????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ?? Mail ?????????????????????????????????????????
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-pasword
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# ?? JWT ??????????????????????????????????????????
app.jwt.secret=your-secret-key
app.jwt.expiration=86400000
app.dev-mode=true

# ?? Upload ???????????????????????????????????????
app.frontend.base-url=your-fe-url
app.frontend.verify-path=your-source
app.frontend.reset-password-path=your-source
app.frontend.oauth2-callback-path=your-url

# ?? Swagger ??????????????????????????????????????
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.csrf.enabled=false
springdoc.packagesToScan=com.ecommerce.backend
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.operationsSorter=method

spring.jpa.properties.hibernate.binary_as_hex=true

spring.security.oauth2.client.registration.google.client-id=your-client-id
spring.security.oauth2.client.registration.google.client-secret=your-oauth-secret
spring.security.oauth2.client.registration.google.scope=email,profile

logging.level.org.springframework.mail=DEBUG
logging.level.com.sun.mail=DEBUG
logging.level.com.ecommerce=DEBUG
logging.level.org.springframework.web=DEBUG
