{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-oauth2-client",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-security-oauth2-client",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-jose",
          "version": {
            "requires": "7.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-oauth2-client-4.0.3.jar",
          "url": "spring-boot-starter-oauth2-client-4.0.3.jar",
          "size": 4814,
          "sha512": "ec43604ab00ebb85a7925a92b3296269fba5e3f7438f3d9a6cd77ca0a43bfbfc117ced01b2c2aa85ca9ef87912b4758b46dc2ef1603d96764f92e3af2428b035",
          "sha256": "a8486e9d1c50d87eb7ea50c2c68866f939b54fddb5fa99dcd9fe7043c99afd04",
          "sha1": "950ac2be918609ed50f096ecedbd682daad5a8f6",
          "md5": "54044ab6a57627283862c3ba9eda74c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-security-oauth2-client",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-jose",
          "version": {
            "requires": "7.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-oauth2-client-4.0.3.jar",
          "url": "spring-boot-starter-oauth2-client-4.0.3.jar",
          "size": 4814,
          "sha512": "ec43604ab00ebb85a7925a92b3296269fba5e3f7438f3d9a6cd77ca0a43bfbfc117ced01b2c2aa85ca9ef87912b4758b46dc2ef1603d96764f92e3af2428b035",
          "sha256": "a8486e9d1c50d87eb7ea50c2c68866f939b54fddb5fa99dcd9fe7043c99afd04",
          "sha1": "950ac2be918609ed50f096ecedbd682daad5a8f6",
          "md5": "54044ab6a57627283862c3ba9eda74c0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-oauth2-client-4.0.3-javadoc.jar",
          "url": "spring-boot-starter-oauth2-client-4.0.3-javadoc.jar",
          "size": 4814,
          "sha512": "ec43604ab00ebb85a7925a92b3296269fba5e3f7438f3d9a6cd77ca0a43bfbfc117ced01b2c2aa85ca9ef87912b4758b46dc2ef1603d96764f92e3af2428b035",
          "sha256": "a8486e9d1c50d87eb7ea50c2c68866f939b54fddb5fa99dcd9fe7043c99afd04",
          "sha1": "950ac2be918609ed50f096ecedbd682daad5a8f6",
          "md5": "54044ab6a57627283862c3ba9eda74c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-oauth2-client-4.0.3-sources.jar",
          "url": "spring-boot-starter-oauth2-client-4.0.3-sources.jar",
          "size": 4814,
          "sha512": "ec43604ab00ebb85a7925a92b3296269fba5e3f7438f3d9a6cd77ca0a43bfbfc117ced01b2c2aa85ca9ef87912b4758b46dc2ef1603d96764f92e3af2428b035",
          "sha256": "a8486e9d1c50d87eb7ea50c2c68866f939b54fddb5fa99dcd9fe7043c99afd04",
          "sha1": "950ac2be918609ed50f096ecedbd682daad5a8f6",
          "md5": "54044ab6a57627283862c3ba9eda74c0"
        }
      ]
    }
  ]
}
