{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-web",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jackson",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-http-converter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webmvc",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-4.0.3.jar",
          "url": "spring-boot-starter-web-4.0.3.jar",
          "size": 4832,
          "sha512": "c5609d147528faafa38a67550fb375ded2525026421d641eb6ac47c066a9391e2265d494c52c279780831e05ce45fedcac61be76d1eee124ddd8d35f17cf4df1",
          "sha256": "3195dbde1fae85dab884092b986ced952f60205f00d1a7a5013bef1c109ed5ef",
          "sha1": "e92dc201a416d2cfde1ed7218f1c2935cbf6ab31",
          "md5": "9ffd18dfb0033201dbf46a7da955fcd7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jackson",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-http-converter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webmvc",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-4.0.3.jar",
          "url": "spring-boot-starter-web-4.0.3.jar",
          "size": 4832,
          "sha512": "c5609d147528faafa38a67550fb375ded2525026421d641eb6ac47c066a9391e2265d494c52c279780831e05ce45fedcac61be76d1eee124ddd8d35f17cf4df1",
          "sha256": "3195dbde1fae85dab884092b986ced952f60205f00d1a7a5013bef1c109ed5ef",
          "sha1": "e92dc201a416d2cfde1ed7218f1c2935cbf6ab31",
          "md5": "9ffd18dfb0033201dbf46a7da955fcd7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-4.0.3-javadoc.jar",
          "url": "spring-boot-starter-web-4.0.3-javadoc.jar",
          "size": 4832,
          "sha512": "c5609d147528faafa38a67550fb375ded2525026421d641eb6ac47c066a9391e2265d494c52c279780831e05ce45fedcac61be76d1eee124ddd8d35f17cf4df1",
          "sha256": "3195dbde1fae85dab884092b986ced952f60205f00d1a7a5013bef1c109ed5ef",
          "sha1": "e92dc201a416d2cfde1ed7218f1c2935cbf6ab31",
          "md5": "9ffd18dfb0033201dbf46a7da955fcd7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-4.0.3-sources.jar",
          "url": "spring-boot-starter-web-4.0.3-sources.jar",
          "size": 4832,
          "sha512": "c5609d147528faafa38a67550fb375ded2525026421d641eb6ac47c066a9391e2265d494c52c279780831e05ce45fedcac61be76d1eee124ddd8d35f17cf4df1",
          "sha256": "3195dbde1fae85dab884092b986ced952f60205f00d1a7a5013bef1c109ed5ef",
          "sha1": "e92dc201a416d2cfde1ed7218f1c2935cbf6ab31",
          "md5": "9ffd18dfb0033201dbf46a7da955fcd7"
        }
      ]
    }
  ]
}
