{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-mail",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-mail",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-mail-4.0.3.jar",
          "url": "spring-boot-starter-mail-4.0.3.jar",
          "size": 4773,
          "sha512": "4510c6918729666fd129f8456b2c27ceba51c2d901444a4fe67deac053227931ef2173cb0c0381ec3eea12e020574cb30804919ae9ad7e822e707a231ba0aede",
          "sha256": "ad8dbb2a7474acc023156f0fcfadedceefb24471a74b939bb8f198b94015a416",
          "sha1": "952c5ef96f2ffc8406cd84da08bf89b4bec1fb9c",
          "md5": "1c1e44b44c8dcf7b55de32bfb2166a6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-mail",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-mail-4.0.3.jar",
          "url": "spring-boot-starter-mail-4.0.3.jar",
          "size": 4773,
          "sha512": "4510c6918729666fd129f8456b2c27ceba51c2d901444a4fe67deac053227931ef2173cb0c0381ec3eea12e020574cb30804919ae9ad7e822e707a231ba0aede",
          "sha256": "ad8dbb2a7474acc023156f0fcfadedceefb24471a74b939bb8f198b94015a416",
          "sha1": "952c5ef96f2ffc8406cd84da08bf89b4bec1fb9c",
          "md5": "1c1e44b44c8dcf7b55de32bfb2166a6d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-mail-4.0.3-javadoc.jar",
          "url": "spring-boot-starter-mail-4.0.3-javadoc.jar",
          "size": 4773,
          "sha512": "4510c6918729666fd129f8456b2c27ceba51c2d901444a4fe67deac053227931ef2173cb0c0381ec3eea12e020574cb30804919ae9ad7e822e707a231ba0aede",
          "sha256": "ad8dbb2a7474acc023156f0fcfadedceefb24471a74b939bb8f198b94015a416",
          "sha1": "952c5ef96f2ffc8406cd84da08bf89b4bec1fb9c",
          "md5": "1c1e44b44c8dcf7b55de32bfb2166a6d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-mail-4.0.3-sources.jar",
          "url": "spring-boot-starter-mail-4.0.3-sources.jar",
          "size": 4773,
          "sha512": "4510c6918729666fd129f8456b2c27ceba51c2d901444a4fe67deac053227931ef2173cb0c0381ec3eea12e020574cb30804919ae9ad7e822e707a231ba0aede",
          "sha256": "ad8dbb2a7474acc023156f0fcfadedceefb24471a74b939bb8f198b94015a416",
          "sha1": "952c5ef96f2ffc8406cd84da08bf89b4bec1fb9c",
          "md5": "1c1e44b44c8dcf7b55de32bfb2166a6d"
        }
      ]
    }
  ]
}
